texture_attributes = [
    "glossy",
    "shiny",
    "matte",
    "rough",
    "bumpy",
    "smooth",
    "shimmering",
    "sparkling",
    "dusty",
    "fuzzy",
    "soft",
    "hard",
    "brittle",
    "flexible",
    "elastic",
    "stiff",
    "rigid",
    "tough",
    "flimsy",
    "delicate",
    "fragile",
    "sturdy",
    "solid",
    "hollow",
    "dense",
    "light",
    "heavy",
    "grainy",
    "slippery",
    "sticky",
    "warm",
    "cool",
    "metallic",
    "pearlescent",
    "satin",
    "dull",
    "reflective",
    "translucent",
    "opaque",
    "homogeneous",
    "heterogeneous",
    "veined",
    "flat",
    "raised",
    "textured",
    "rugged",
    "water-resistant",
    "light-absorbing",
    "dust-repellent",
    "cozy",
    "luxurious",
    "rustic",
    "weathered",
    "polished",
    "aged",
    "green",
    "brown",
    "yellow",
    "orange",
    "red",
    "blue",
    "purple",
    "pink",
    "white",
    "black",
    "grey",
    "silver",
    "gold",
    "cyan",
    "magenta",
    "turquoise",
    "ivory",
    "tan",
    "beige",
    "navy",
    "maroon",
    "charcoal",
    "teal",
    "olive",
    "peach",
    "lavender",
    "uniform",
    "abstract",
    "geometric",
    "random",
    "symmetrical",
    "asymmetrical",
    "striped",
    "checked",
    "paisley",
    "plaid",
    "houndstooth",
    "polka-dot",
    "herringbone",
    "chevron",
    "argyle",
    "non-reflective",
    "marbled",
    "grained",
    "streaked",
    "spotted",
    "speckled",
    "dappled",
    "mottled",
    "flecked",
    "patched",
    "layered",
    "deep",
    "shallow",
    "pitted",
    "embossed",
    "engraved",
    "new",
    "old",
    "worn",
    "damaged",
    "antique",
    "vintage",
    "distressed",
    "refurbished",
    "restored",
    "pristine",
    "immaculate",
    "tarnished",
    "faded",
    "marble",
    "granite",
    "wood",
    "metal",
    "glass",
    "plastic",
    "fabric",
    "leather",
    "paper",
    "cardboard",
    "concrete",
    "brick",
    "stone",
    "sand",
    "dirt",
    "mud",
    "clay",
    "ceramic",
    "porcelain",
    "rubber",
    "sponge",
    "foam",
    "felt",
    "velvet",
    "silk",
    "cotton",
    "wool",
    "linen",
    "denim",
    "lace",
    "tweed",
    "nylon",
    "polyester",
    "acrylic",
    "spandex",
    "suede",
    "mesh",
    "bamboo",
    "hemp",
    "leaf pattern",
    "floral pattern",
    "animal pattern",
    "zebra pattern",
    "tiger pattern",
    "leopard pattern",
    "cheetah pattern",
    "giraffe pattern",
    "snake pattern",
    "crocodile pattern",
    "camouflage pattern",
    "mosaic pattern",
    "kaleidoscope pattern",
    "mandala pattern",
    "tartan pattern",
    "batik pattern",
    "ikat pattern",
    "quilted pattern",
    "glittering",
    "mirrored",
    "satin-finish",
    "carbon fiber",
    "knitted",
    "crocheted",
    "embroidered",
    "pleated",
    "crinkled",
    "crumpled",
    "woven",
    "braided",
    "perforated",
    "padded",
    "quilted",
    "thermal",
    "insulated",
    "gauzy",
    "translucent-finish",
    "iridescent",
    "opalescent",
    "neon",
    "pastel",
    "vibrant",
    "dull-finish",
    "chalky",
    "silky-smooth",
    "rubbery",
    "gummy",
    "waxy",
    "oily",
    "soapy",
    "milky",
    "crystal-clear",
    "frosted",
    "etched",
    "blurred",
    "swirled",
    "twisted",
    "coiled",
    "looped",
    "interwoven",
    "knotted",
    "spiral",
    "diagonal",
    "crosshatched",
    "lacy",
    "beaded",
    "sequined",
    "flocked",
    "brushed metal",
    "anodized",
    "galvanized",
    "powder-coated",
    "acid-washed",
    "sun-bleached",
    "peeling",
    "cracked",
    "chipped",
    "burnished",
    "oxidized",
    "corroded",
    "stained",
    "dyed",
    "tie-dye pattern",
    "ombre",
    "gradient",
    "speckled paint",
    "splattered paint",
    "marbleized",
    "woodgrain",
    "cork",
    "terrazzo",
    "bamboo texture",
    "reed",
    "sisal",
    "sea grass",
    "jute",
    "chalkboard",
    "magnetic",
    "glazed",
    "unglazed",
    "raw",
    "burnt",
    "smoked",
    "sanded",
    "planed",
    "rough-cut",
    "varnished",
    "unvarnished",
    "waxed",
    "oil-finished",
    "shellac-finished",
    "lacquered",
    "patina",
    "brushed",
    "hammered",
    "spun",
    "wrought",
    "forged",
    "cast",
    "molded",
    "3D printed",
    "laminated",
    "veneered",
    "inlaid",
    "gilded",
    "silvered",
    "leafed",
    "foiled",
    "embossed pattern",
    "debossed pattern",
    "puzzle pattern",
    "geometric pattern",
    "optical illusion pattern",
    "holographic pattern",
    "psychedelic pattern",
    "pop art pattern",
    "art deco pattern",
    "Victorian pattern",
    "Baroque pattern",
    "Renaissance pattern",
    "gothic pattern",
    "Celtic pattern",
    "tribal pattern",
    "Ethnic pattern",
    "folk pattern",
    "historical pattern",
]

adjectives = [
    "rotten",
    "big",
    "small",
    "many",
    "burning",
    "melting",
    "shattered",
    "dried",
    "sliced",
    "moldy",
    "glistening",
    "fluffy",
    "plush",
    "opaque",
    "wrinkled",
    "frosted",
    "antique",
    "futuristic",
    "cracked",
    "glowing",
    "glossy",
    "translucent",
    "gothic",
    "young",
    "old",
    "rustic",
    "two",
    "multiple",
    "group",
    "shiny",
    "dull",
    "colorful",
    "floating",
    "winged",
    "soggy",
    "ancient",
    "tiny",
    "enormous",
    "skeletal",
    "hairless",
    "furry",
    "grimy",
    "frozen",
    "dusty",
    "muddy",
    "bubbly",
    "spiky",
    "slimy",
    "scaly",
    "feathery",
    "hairy",
    "fuzzy",
    "smooth",
    "rough",
    "gleaming",
    "heavy",
    "wet",
    "dry",
    "aged",
    "transparent",
    "empty",
    "full",
]

art_types = [
    "photo",
    "painting",
    "sketch",
    "sculpture",
    "photograph",
    "drawing",
    "tapestry",
    "mosaic",
    "carving",
    "pottery",
    "ceramic",
    "origami",
    "stained glass",
    "engraving",
    "watercolor painting",
    "oil painting",
    "acrylic painting",
    "charcoal drawing",
    "pencil drawing",
    "pastel drawing",
    "ink drawing",
    "digital painting",
    "collage",
    "mixed media",
    "woodcut",
    "lithograph",
    "etching",
    "engraving",
    "comic drawing",
    "cartoon",
    "animation",
    "illustration",
    "concept art",
    "conceptual art",
    "3D rendering",
    "digital art",
    "traditional art",
    "abstract art",
    "realistic art",
    "minimalist art",
    "abstract art",
]


creatures = [
    "cat",
    "dog",
    "bird",
    "elf",
    "fairy",
    "dragon",
    "phoenix",
    "griffin",
    "unicorn",
    "troll",
    "goblin",
    "mermaid",
    "kraken",
    "centaur",
    "sphinx",
    "werewolf",
    "vampire",
    "zombie",
    "giant",
    "sprite",
    "nymph",
    "ogre",
    "basilisk",
    "pegasus",
    "djinn",
    "yeti",
    "leviathan",
    "chimera",
    "golem",
    "succubus",
    "incubus",
    "elemental",
    "dryad",
    "satyr",
    "harpy",
    "manticore",
    "hydra",
    "selkie",
    "kelpie",
    "banshee",
    "cerberus",
    "wyvern",
    "minotaur",
    "jabberwock",
    "behemoth",
    "kraken",
    "cyclops",
    "siren",
    "naga",
    "wendigo",
    "doppelganger",
    "rakshasa",
    "kitsune",
    "oni",
    "tanuki",
    "kobold",
    "gremlin",
    "boggart",
    "wraith",
    "shade",
    "lich",
    "hobgoblin",
    "ghoul",
    "djinn",
    "tarasque",
    "chimera",
    "ifrit",
    "selkie",
    "faun",
    "seraph",
    "cherub",
    "archangel",
    "demon",
    "angel",
    "wolf",
    "elephant",
    "lion",
    "giraffe",
    "bear",
    "moose",
    "fox",
    "eagle",
    "shark",
    "dolphin",
    "whale",
    "penguin",
    "otter",
    "raccoon",
    "leopard",
    "cheetah",
    "hippopotamus",
    "rhinoceros",
    "zebra",
    "squirrel",
    "rabbit",
    "kangaroo",
    "koala",
    "panda",
    "lynx",
    "deer",
    "crocodile",
    "alligator",
    "skunk",
    "falcon",
    "parrot",
    "owl",
    "hawk",
    "vulture",
    "snake",
    "lizard",
    "turtle",
    "octopus",
    "lobster",
    "starfish",
    "coral",
    "jellyfish",
    "seahorse",
    "camel",
    "donkey",
    "mule",
    "horse",
    "pig",
    "sheep",
    "cow",
    "goat",
    "chicken",
    "turkey",
    "duck",
    "goose",
    "ant",
    "bee",
    "butterfly",
    "caterpillar",
    "moth",
    "cockroach",
    "spider",
    "scorpion",
    "antelope",
    "bat",
    "beaver",
    "buffalo",
    "bison",
    "chameleon",
    "clownfish",
    "cod",
    "crab",
    "cuttlefish",
    "deer",
    "dingo",
    "emu",
    "ferret",
    "flamingo",
    "frog",
    "gecko",
    "gibbon",
    "goldfish",
    "guinea pig",
    "hamster",
    "hedgehog",
    "hermit crab",
    "iguana",
    "jackal",
    "jaguar",
    "lemur",
    "macaw",
    "manatee",
    "meerkat",
    "mink",
    "mole",
    "mongoose",
    "monkey",
    "ostrich",
    "otter",
    "owl",
    "panda",
    "panther",
    "parakeet",
    "pelican",
    "pigeon",
    "platypus",
    "porcupine",
    "possum",
    "prawn",
    "quail",
    "quokka",
    "raccoon",
    "rat",
    "rattlesnake",
    "reindeer",
    "salamander",
    "salmon",
    "sand dollar",
    "sardine",
    "scorpion",
    "sea cucumber",
    "sea lion",
    "sea urchin",
    "seagull",
    "shrimp",
    "sloth",
    "slug",
    "snail",
    "sparrow",
    "stingray",
    "swan",
    "tiger",
    "toad",
    "toucan",
    "tuna",
    "walrus",
    "wasp",
    "weasel",
    "whale shark",
    "woodpecker",
    "worm",
    "wombat",
    "zebu",
    "zebra shark",
    "cockatrice",
    "roc",
    "thunderbird",
    "fenrir",
    "jormungandr",
    "sleipnir",
    "valkyrie",
    "nephilim",
    "gorgon",
    "lamia",
    "sylph",
    "nixie",
    "undine",
    "brownie",
    "leprechaun",
    "bandersnatch",
    "hippogriff",
    "ouroboros",
    "amphisbaena",
    "kappa",
    "tengu",
    "bakeneko",
    "tsukumogami",
    "yokai",
    "axolotl",
    "capybara",
    "dugong",
    "echidna",
    "fennec fox",
    "gazelle",
    "hornbill",
    "ibex",
    "jerboa",
    "kinkajou",
    "loris",
    "numbat",
    "okapi",
    "pangolin",
    "quetzal",
    "tapir",
    "uakari",
    "vole",
    "xenops",
    "yapok",
    "anglerfish",
    "barracuda",
    "conger eel",
    "dugong",
    "electric eel",
    "flying fish",
    "grouper",
    "hammerhead shark",
    "lionfish",
    "manta ray",
    "narwhal",
    "oarfish",
    "pufferfish",
    "ray",
    "swordfish",
    "triggerfish",
    "assassin bug",
    "bombardier beetle",
    "cicada",
    "dragonfly",
    "earwig",
    "firefly",
    "grasshopper",
    "honeybee",
    "katydid",
    "ladybug",
    "mantis",
    "praying mantis",
    "scarab beetle",
    "tarantula",
    "walkingstick",
    "albatross",
    "blackbird",
    "cardinal",
    "dove",
    "egret",
    "finch",
    "grackle",
    "hummingbird",
    "ibis",
    "kingfisher",
    "loon",
    "meadowlark",
    "nightingale",
    "oriole",
    "ptarmigan",
    "robin",
    "sandpiper",
    "thrush",
    "warbler",
    "yellowthroat",
    # Additional mythological creatures
    "grootslang",
    "dropbear",
    "bunyip",
    "chupacabra",
    "mothman",
    "jersey devil",
    "bigfoot",
    "sasquatch",
    "yowie",
    "kikimora",
    "leshy",
    "vodyanoy",
    "domovoi",
    "rusalka",
    "baba yaga",
    "alkonost",
    "gamayun",
    "sirin",
    "indrik",
    "zilant",
    "amarok",
    "akhlut",
    "adlet",
    "qilin",
    "fenghuang",
    "baku",
    "nue",
    "gashadokuro",
    "jorōgumo",
    "ningyo",
    # Additional prehistoric creatures
    "tyrannosaurus rex",
    "velociraptor",
    "stegosaurus",
    "triceratops",
    "pterodactyl",
    "brontosaurus",
    "ankylosaurus",
    "diplodocus",
    "pachycephalosaurus",
    "parasaurolophus",
    "spinosaurus",
    "allosaurus",
    "megalodon",
    "mammoth",
    "saber-toothed tiger",
    "dodo",
    # Additional insects
    "silverfish",
    "termite",
    "hornet",
    "yellowjacket",
    "paper wasp",
    "carpenter ant",
    "fire ant",
    "army ant",
    "bullet ant",
    "weevil",
    "rhinoceros beetle",
    "hercules beetle",
    "atlas beetle",
    "dung beetle",
    "firefly",
    "lightning bug",
    "june bug",
    "stink bug",
    "wheel bug",
    # Additional sea creatures
    "leafy seadragon",
    "weedy seadragon",
    "ribbon eel",
    "garden eel",
    "frogfish",
    "stoplight parrotfish",
    "wolffish",
    "moray eel",
    "boxfish",
    "cowfish",
    "seamoth",
    "sea robin",
    "batfish",
    "pinnate spadefish",
    "lookdown fish",
    "remora",
    "wobbegong",
    # Additional birds
    "secretary bird",
    "shoebill",
    "hoatzin",
    "kakapo",
    "kea",
    "cassowary",
    "harpy eagle",
    "philippine eagle",
    "quetzal",
    "frigate bird",
    "bird of paradise",
    "resplendent quetzal",
    "cock-of-the-rock",
    "ruff",
    "great argus",
    "sage grouse",
    # Additional mammals
    "binturong",
    "fossa",
    "tayra",
    "coatimundi",
    "kinkajou",
    "tamandua",
    "pangolin",
    "tenrec",
    "aye-aye",
    "tarsier",
    "slow loris",
    "pygmy hippopotamus",
    "okapi",
    "gerenuk",
    "saiga antelope",
    "markhor",
    "takin",
    "bharal",
    "gaur",
    # Additional reptiles and amphibians
    "tuatara",
    "thorny devil",
    "frilled lizard",
    "mata mata",
    "chinese giant salamander",
    "hellbender",
    "olm",
    "axolotl",
    "glass frog",
    "poison dart frog",
    "surinam toad",
    "purple frog",
    "flying lizard",
    "basilisk lizard",
    "marine iguana",
    # # Adding fantasy professions and roles
    # 'alchemist', 'archmage', 'artificer', 'astrologer', 'battlemage',
    # 'beastmaster', 'berserker', 'bladedancer', 'bloodmage', 'bounty hunter',
    # 'channeler', 'chronomancer', 'conjurer', 'cryptkeeper', 'cursebreaker',
    # 'darknight', 'deathknight', 'demonhunter', 'diviner', 'dragonrider',
    # 'dragoon', 'dreamwalker', 'druid', 'elementalist', 'enchanter',
    # 'geomancer', 'gladiator', 'gravewalker', 'harbinger', 'healer',
    # 'hexblade', 'hierophant', 'illusionist', 'inquisitor', 'lorekeeper',
    # 'mage hunter', 'magister', 'monk', 'necromancer', 'oracle',
    # 'paladin', 'planewalker', 'priest', 'pyromancer', 'ranger',
    # 'reaper', 'rogue', 'runesmith', 'saber', 'sage',
    # 'scribe', 'seamstress', 'shadowblade', 'shaman', 'shapeshifter',
    # 'skald', 'soothsayer', 'sorcerer', 'spellblade', 'spellbreaker',
    # 'summoner', 'swashbuckler', 'templar', 'thaumaturge', 'theurgist',
    # 'time mage', 'transmuter', 'warlock', 'warmage', 'warrior',
    # 'wayfinder', 'witch doctor', 'witcher', 'zealot',
    # # Medieval/Fantasy Craftsmen and Specialists
    # 'apothecary', 'armorer', 'blacksmith', 'bowyer', 'fletcher',
    # 'glassblower', 'herbalist', 'jeweler', 'leatherworker', 'mason',
    # 'merchant', 'mystic', 'navigator', 'poisoner', 'potionmaster',
    # 'runescriber', 'seer', 'siegemaster', 'spymaster', 'strategist',
    # 'taskmaster', 'taxidermist', 'tinker', 'weaponsmith', 'woodcarver',
    # # Guild and Organization Members
    # 'assassin', 'guild master', 'mercenary', 'night blade', 'pathfinder',
    # 'scholar', 'sentinel', 'shadowkeeper', 'thieves guild member', 'treasure hunter',
    # 'monster hunter', 'dragon slayer', 'beast tamer', 'creature handler',
    # # Royal and Noble Positions
    # 'archduke', 'baron', 'count', 'duke', 'emperor',
    # 'king', 'knight', 'lord', 'noble', 'prince',
    # 'princess', 'queen', 'royal guard', 'squire',
    # # Maritime Fantasy Roles
    # 'navigator', 'pirate', 'sailor', 'sea witch', 'ship captain',
    # 'storm caller', 'tide mage', 'wave runner',
    # # Tribal and Nature-Based Roles
    # 'earthkeeper', 'forest walker', 'hedge witch', 'spirit guide',
    # 'stoneshaper', 'tribal elder', 'wind whisperer', 'wyrdweaver',
    # # Magical Researchers and Scholars
    # 'arcanist', 'demonologist', 'etherealist', 'occultist',
    # 'planar scholar', 'runemaster', 'spell archaeologist', 'thaumaturgist',
    # # Combat Specialists
    # 'battle priest', 'blood knight', 'chaos warrior', 'dragon knight',
    # 'duelist', 'holy warrior', 'shadow warrior', 'spell sword',
    # 'war priest', 'weapons master'
]


adjectives = [
    "cute",
    "scary",
    "steampunk",
    "dystopian",
    "utopian",
    "cyberpunk",
    "fantasy",
    "futuristic",
    "medieval",
    "mythical",
    "mystical",
    "otherworldly",
    "ethereal",
    "celestial",
    "arcane",
    "ancient",
    "haunted",
    "glowing",
    "shadowy",
    "enigmatic",
    "feral",
    "primal",
    "macabre",
    "twisted",
    "mechanical",
    "apocalyptic",
    "radiant",
    "glistening",
    "ominous",
    "whimsical",
    "exquisite",
    "grotesque",
    "surreal",
    "mechanized",
    "iridescent",
    "chromatic",
    "ornate",
    "runic",
    "savage",
    "ornamental",
    "barbaric",
    "fabled",
    "charismatic",
    "phantasmal",
    "eldritch",
    "ceremonial",
    "sinister",
    "regal",
    "demonic",
    "angelic",
    "primeval",
    "arcadian",
    "verdant",
    "desolate",
    "frosty",
    "infernal",
    "spectral",
    "bioluminescent",
    "luminescent",
    "ominous",
    "arcane",
    "serene",
    "hyperreal",
    "exuberant",
    "monolithic",
    "petrified",
    "mirrored",
    "fractured",
    "sublime",
    "geometric",
    "polychromatic",
    "shadow-cast",
    "obsidian",
    "luminous",
    "radiating",
    "labyrinthine",
    "spirited",
    "haunting",
    "chromatic",
    "tempestuous",
    "volcanic",
    "frostbitten",
    "enchanted",
    "bewitched",
    "shimmering",
    "melancholic",
    "chimerical",
    "esoteric",
    "transcendent",
    "ancillary",
    "phantomlike",
    "fabled",
    "gliding",
    "soaring",
    "webbed",
    "prehistoric",
    "glacial",
    "swift",
    "venomous",
    "thorned",
    "crystalline",
    "celestial",
    "rift-born",
    "abyssal",
    "storm-touched",
    "void-like",
    "silken",
    "carapaced",
    "ethereal",
    "heavenly",
    "ancient-blooded",
    "nightmarish",
    "moonlit",
    "starry",
    "daylit",
    "ferocious",
    "eternal",
    "chaotic",
    "titanic",
    "blazing",
    "icy",
    "electric",
    "stormy",
    "lava-born",
    "rooted",
    "vined",
    "sea-bound",
    "sky-bound",
    "mountainous",
    "deep-dwelling",
    "dreadful",
    "iridescent",
    "glittering",
    "tail",
    "timeless",
    "ember-glowing",
    "dawn-touched",
    "dusky",
    "half-shadowed",
    # Physical Characteristics
    "scaled",
    "feathered",
    "horned",
    "winged",
    "clawed",
    "fanged",
    "armored",
    "spined",
    "tusked",
    "tentacled",
    "barbed",
    "spiked",
    "plated",
    "furred",
    "maned",
    "crested",
    "hooded",
    "spotted",
    "striped",
    "mottled",
    "bristled",
    "ridged",
    "segmented",
    "finned",
    "plumed",
    "antlered",
    "taloned",
    "beaked",
    "shell-backed",
    "quilled",
    # Elemental
    "thunderous",
    "flame-wreathed",
    "frost-touched",
    "wind-swept",
    "earth-bound",
    "shadow-wrapped",
    "light-blessed",
    "water-born",
    "lightning-struck",
    "ice-crowned",
    "magma-forged",
    "storm-bred",
    "mist-shrouded",
    "fog-veiled",
    "sand-scoured",
    "snow-cloaked",
    # Magical/Mystical
    "spell-bound",
    "curse-marked",
    "rune-etched",
    "charm-woven",
    "hex-touched",
    "magic-infused",
    "enchantment-laden",
    "ritual-blessed",
    "oracle-blessed",
    "prophecy-marked",
    "destiny-touched",
    "fate-bound",
    "dream-woven",
    "nightmare-touched",
    "vision-blessed",
    "mystic-born",
    # # Environmental
    # 'cave-dwelling', 'forest-born', 'desert-bred', 'mountain-raised',
    # 'swamp-lurking', 'jungle-stalking', 'reef-dwelling', 'tundra-born',
    # 'valley-roaming', 'plains-running', 'cliff-nesting', 'tree-dwelling',
    # # Behavioral
    # 'prowling', 'stalking', 'lurking', 'hunting', 'ambushing', 'striking',
    # 'pouncing', 'swooping', 'darting', 'charging', 'stampeding', 'swarming',
    # 'nesting', 'burrowing', 'migrating', 'hibernating', 'territorial',
    # # Time-related
    # 'nocturnal', 'diurnal', 'crepuscular', 'seasonal', 'ancient',
    # 'primordial', 'ageless', 'eternal', 'ephemeral', 'temporal',
    # 'dawn-rising', 'dusk-falling', 'midnight-prowling', 'noon-basking',
    # # Size and Scale
    # 'colossal', 'gigantic', 'massive', 'towering', 'enormous', 'tiny',
    # 'miniature', 'diminutive', 'mammoth', 'microscopic', 'hulking',
    # 'looming', 'towering', 'dominating', 'overwhelming', 'imposing',
    # Atmospheric
    "foreboding",
    "menacing",
    "threatening",
    "intimidating",
    "terrifying",
    "awe-inspiring",
    "majestic",
    "magnificent",
    "resplendent",
    "grand",
    "imposing",
    "mysterious",
    "enigmatic",
    "cryptic",
    "obscure",
    "veiled",
    # Color and Appearance
    "prismatic",
    "opalescent",
    "pearlescent",
    "translucent",
    "transparent",
    "opaque",
    "metallic",
    "crystalline",
    "rainbow-hued",
    "multi-colored",
    "camouflaged",
    "phosphorescent",
    "incandescent",
    "reflective",
    # # Sound-related
    # 'thundering', 'roaring', 'howling', 'screaming', 'whispering',
    # 'hissing', 'chirping', 'singing', 'humming', 'buzzing', 'droning',
    # 'bellowing', 'trumpeting', 'shrieking', 'growling', 'rumbling'
]


types_of_chairs = [
    "Armchair",
    "Rocking chair",
    "Recliner",
    "Dining chair",
    "Office chair",
    "Lounge chair",
    "Folding chair",
    "Bean bag chair",
    "Stool",
    "Bar stool",
    "Wheelchair",
    "Deck chair",
    "High chair",
    "Chaise lounge",
    "Adirondack chair",
    "Gaming chair",
    "Accent chair",
    "Wingback chair",
    "Director's chair",
    "Papasan chair",
]


chair_parts = [
    "Legs",
    "Seat",
    "Backrest",
    "Armrests",
    "Headrest",
    "Footrest",
    "Chair Base",
    "Cushion",
]

keywords = ["head", "legs", "arms", "wings", "shirt", "pants", "skirt", "hat", "object"]

background = [
    "a bustling city square",
    "a quiet village street",
    "an enchanted forest clearing",
    "a snowy mountain peak",
    "a sunlit beach",
    "a dark alleyway",
    "a vibrant marketplace",
    "a hidden cave",
    "a foggy dock",
    "an abandoned factory",
    "a modern urban park",
    "a serene lakeside",
    "a quaint countryside",
    "a misty swamp",
    "a futuristic metropolis",
    "a desert oasis",
    "a dense jungle",
    "a medieval castle courtyard",
    "a lively carnival",
    "a remote island",
    "a tranquil Zen garden",
    "a bustling train station",
    "a sprawling vineyard",
    "a crumbling ruin",
    "a lively seaport",
    "an ancient temple",
    "a snowy forest",
    "a quiet library",
    "a high-tech laboratory",
    "a secret garden",
    "a war-torn battlefield",
    "a picturesque harbor",
    "a vibrant art district",
    "a scenic mountain pass",
    "a sprawling shopping mall",
    "a rural farmhouse",
    "a neon-lit street",
    "a rustic barn",
    "a busy airport terminal",
    "a serene monastery",
    "a remote desert highway",
    "a whimsical treehouse",
    "a sun-drenched plaza",
    "a stormy lighthouse",
    "a busy city rooftop",
    "a secluded cabin",
    "a glimmering waterfall",
    "a craggy canyon",
    "a cobblestone street",
    "an ancient amphitheater",
    "a solid blue background",
    "a solid red background",
    "a solid green background",
    "a solid yellow background",
    "a solid purple background",
    "a solid orange background",
    "a solid black background",
    "a solid white background",
    "a solid gray background",
    "an abandoned amusement park",
    "a hidden underground bunker",
    "a mystical floating island",
    "a derelict spaceship hangar",
    "a futuristic space colony",
    "a surreal dreamscape",
    "a ruined Gothic cathedral",
    "a steampunk airship dock",
    "a haunted mansion",
    "a labyrinthine cave network",
    "a forgotten arboretum",
    "a remote arctic research station",
    "a magical glade at twilight",
    "a floating observatory in the clouds",
    "a crystalline cave filled with glowing minerals",
    "a ruined ancient fortress",
    "a mystical ice palace",
    "a ghostly shipwreck on a foggy shore",
    "an eerie abandoned carnival",
    "a forgotten underground city",
    "a lunar colony",
    "a vibrant coral reef underwater",
    "a mysterious alien temple",
    "a surreal mirrored labyrinth",
    "a crystalline frozen lake",
    "an ancient stone circle in a misty field",
    "a cosmic nebula",
    "a surreal underwater abyss",
    "a bioluminescent forest at night",
    "an abandoned underground subway station",
]

characters_with_consistent_looks = [
    "Mickey Mouse",
    "Minnie Mouse",
    "Donald Duck",
    "Daisy Duck",
    "Goofy",
    # "Pluto",
    "Winnie the Pooh",
    # "Piglet",
    "Tigger",
    "Eeyore",
    # "Christopher Robin",
    # "Kanga",
    # "Roo",
    # "Rabbit",
    # "Owl",
    # "Dumbo",
    # "Pinocchio",
    # "Jiminy Cricket",
    # "Peter Pan",
    # "Captain Hook",
    # "Tinker Bell",
    # "Snow White",
    # "Cinderella",
    # "Aurora",
    # "Flounder",
    # "Sebastian",
    # "Ursula",
    # "Lumiere",
    # "Cogsworth",
    # "Mrs. Potts",
    # "Chip",
    # "Iago",
    # "Magic Carpet",
    # "Mushu",
    "Olaf",
    # "Sven",
    # "Sleepy",
    # "Grumpy",
    # "Happy",
    # "Doc",
    # "Bashful",
    # "Sneezy",
    # "Dopey",
    # "Woody",
    "Buzz Lightyear",
    # "Jessie",
    "Mr. Potato Head",
    # "Mrs. Potato Head",
    # "Slinky Dog",
    # "Rex",
    # "Hamm",
    "Mike Wazowski",
    "James P. Sullivan",
    # "Nemo",
    # "Dory",
    # "Marlin",
    "WALL-E",
    # "EVE",
    "Lightning McQueen",
    # "Mater",
    # "Sally",
    # "Remy",
    # "Emile",
    # "Anton Ego",
    # "Russell",
    # "Carl Fredricksen",
    # "Dug",
    # "Kevin",
    "Bugs Bunny",
    "Daffy Duck",
    # "Elmer Fudd",
    # "Porky Pig",
    # "Sylvester",
    # "Tweety",
    # "Yosemite Sam",
    # "Foghorn Leghorn",
    # "Marvin the Martian",
    # "Pepe Le Pew",
    # "Speedy Gonzales",
    # "Tasmanian Devil",
    # "Road Runner",
    # "Wile E. Coyote",
    "Scooby-Doo",
    # "Shaggy Rogers",
    # "Fred Jones",
    # "Daphne Blake",
    # "Velma Dinkley",
    # "Scrappy-Doo",
    # "Yogi Bear",
    # "Boo-Boo Bear",
    # "Ranger Smith",
    # "Huckleberry Hound",
    # "Quick Draw McGraw",
    # "Augie Doggie",
    # "Doggie Daddy",
    # "Snagglepuss",
    # "Top Cat",
    # "Benny the Ball",
    # "Choo-Choo",
    # "Brain",
    # "Fancy-Fancy",
    # "Spook",
    # "Magilla Gorilla",
    # "Wally Gator",
    # "Atom Ant",
    # "Secret Squirrel",
    # "Morocco Mole",
    # "Fred Flintstone",
    # "Wilma Flintstone",
    # "Pebbles Flintstone",
    # "Barney Rubble",
    # "Betty Rubble",
    # "Bamm-Bamm Rubble",
    # "Dino",
    # "George Jetson",
    # "Jane Jetson",
    # "Judy Jetson",
    # "Elroy Jetson",
    # "Astro",
    # "Rosie",
    # "Hong Kong Phooey",
    # "Captain Caveman",
    # "Jabberjaw",
    # "Jonny Quest",
    # "Hadji",
    # "Race Bannon",
    # "Dr. Benton Quest",
    # "Dexter",
    # "Dee Dee",
    # "Mandark",
    # "Blossom",
    # "Bubbles",
    # "Buttercup",
    # "Mojo Jojo",
    # "Professor Utonium",
    # "Johnny Bravo",
    # "Courage",
    # "Eustace Bagge",
    # "Muriel Bagge",
    # "Ed",
    # "Edd",
    # "Eddy",
    # "Plank",
    "SpongeBob SquarePants",
    # "Patrick Star",
    "Squidward Tentacles",
    "Mr. Krabs",
    # "Sheldon J. Plankton",
    # "Sandy Cheeks",
    # "Gary the Snail",
    # "Pearl Krabs",
    # "Larry the Lobster",
    # "Jimmy Neutron",
    # "Carl Wheezer",
    # "Sheen Estevez",
    # "Cindy Vortex",
    # "Libby Folfax",
    # "Timmy Turner",
    # "Cosmo",
    # "Wanda",
    # "Vicky",
    # "Denzel Crocker",
    # "Chester McBadbat",
    # "A.J.",
    # "Danny Fenton",
    # "Sam Manson",
    # "Tucker Foley",
    # "Tommy Pickles",
    # "Chuckie Finster",
    # "Phil DeVille",
    # "Lil DeVille",
    # "Angelica Pickles",
    # "Kimi Finster",
    # "Susie Carmichael",
    # "Reptar",
    # "CatDog",
    # "Norbert Beaver",
    # "Daggett Beaver",
    # "Rocko",
    # "Heffer Wolfe",
    # "Filburt",
    # "Spunky",
    # "Ren Hoek",
    # "Stimpy",
    # "Arnold Shortman",
    # "Gerald Johanssen",
    # "Helga Pataki",
    # "Phoebe Heyerdahl",
    # "Harold Berman",
    # "Skipper",
    # "Kowalski",
    # "Rico",
    # "Private",
    # "King Julien",
    # "Mort",
    # "Maurice",
    "Garfield",
    # "Odie",
    # "Jon Arbuckle",
    # "Nermal",
    # "Pooky",
    # "Charlie Brown",
    "Snoopy",
    # "Woodstock",
    # "Lucy Van Pelt",
    # "Linus Van Pelt",
    # "Schroeder",
    # "Franklin",
    # "Peppermint Patty",
    # "Marcie",
    # "Sally Brown",
    # "Pigpen",
    "R2-D2",
    "BB-8",
    "Chewbacca",
    "Jar Jar Binks",
    # "Admiral Ackbar",
    "Darth Vader",
    "Jabba the Hutt",
    # "K-2SO",
    "Kermit the Frog",
    # "Fozzie Bear",
    # "Gonzo",
    # "Animal",
    # "Swedish Chef",
    # "Rowlf the Dog",
    # "Dr. Teeth",
    # "Floyd Pepper",
    # "Janice",
    # "Zoot",
    # "Lips",
    # "Scooter",
    # "Rizzo the Rat",
    # "Pepe the King Prawn",
    # "Beaker",
    # "Bunsen Honeydew",
    # "Sam Eagle",
    # "Statler",
    # "Waldorf",
    "Pikachu",
    "Bulbasaur",
    "Charmander",
    "Squirtle",
    # "Jigglypuff",
    # "Meowth",
    # "Psyduck",
    # "Togepi",
    # "Wobbuffet",
    # "Mewtwo",
    # "Eevee",
    # "Snorlax",
    # "Gengar",
    # "Onix",
    # "Magikarp",
    # "Caterpie",
    # "Oddish",
    # "Zapdos",
    # "Moltres",
    # "Articuno",
    # "Lugia",
    # "Ho-Oh",
    # "Celebi",
    # "Groudon",
    # "Kyogre",
    # "Rayquaza",
    # "Lucario",
    # "Mimikyu",
    "Mario",
    "Luigi",
    # "Princess Peach",
    # "Toad",
    "Bowser",
    # "Yoshi",
    # "Wario",
    # "Waluigi",
    # "Donkey Kong",
    # "Diddy Kong",
    # "Dixie Kong",
    "Kirby",
    # "Meta Knight",
    # "King Dedede",
    # "Tom Nook",
    # "Timmy",
    # "Tommy",
    # "K.K. Slider",
    # "Isabelle",
    # "Brewster",
    # "Mr. Resetti",
    # "Flick",
    # "Celeste",
    # "Blathers",
    "Sonic the Hedgehog",
    # "Miles Tails Prower",
    # "Knuckles the Echidna",
    # "Dr. Eggman",
    # "Amy Rose",
    # "Shadow the Hedgehog",
    # "Big the Cat",
    # "Blaze the Cat",
    # "Cream the Rabbit",
    # "Vector the Crocodile",
    # "Espio the Chameleon",
    # "Charmy Bee",
    # "Rayman",
    # "Globox",
    # "Pac-Man",
    # "Ms. Pac-Man",
    # "Blinky",
    # "Pinky",
    # "Inky",
    # "Clyde",
    # "Slime",
    # "Chocobo",
    # "Mega Man",
    # "Proto Man",
    # "Dr. Wily",
    # "Roll",
    # "Rush",
    # "M. Bison",
    "Totoro",
    # "Catbus",
    # "Jiji",
    # "No-Face",
    # "Doraemon",
    # "Nobita Nobi",
    # "Shizuka Minamoto",
    # "Takashi Gouda",
    # "Suneo Honekawa",
    # "Shin-chan Nohara",
    # "Hiroshi Nohara",
    # "Misae Nohara",
    # "Himawari Nohara",
    # "Shiro",
    # "Anpanman",
    # "Baikinman",
    # "Dokinchan",
    # "Hello Kitty",
    # "My Melody",
    # "Keroppi",
    # "Badtz-Maru",
    # "Pompompurin",
    # "Cinnamoroll",
    # "Kuromi",
    # "Asterix",
    # "Obelix",
    # "Dogmatix",
    # "Getafix",
    # "Vitalstatistix",
    # "Tintin",
    # "Snowy",
    # "Captain Haddock",
    # "Thomson",
    # "Thompson",
    # "Professor Calculus",
    "Papa Smurf",
    "Smurfette",
    # "Brainy Smurf",
    # "Clumsy Smurf",
    # "Hefty Smurf",
    # "Jokey Smurf",
    # "Vanity Smurf",
    # "Greedy Smurf",
    # "Baker Smurf",
    # "Handy Smurf",
    # "Farmer Smurf",
    # "Gargamel",
    # "Azrael",
    # "Lucky Luke",
    # "Joe Dalton",
    # "Jack Dalton",
    # "William Dalton",
    # "Averell Dalton",
    # "Oggy",
    # "Dee Dee",
    # "Marky",
    # "Joey",
    # "Chip",
    # "Dale",
    # "Woody Woodpecker",
    # "Andy Panda",
    # "Chilly Willy",
    # "Betty Boop",
    # "Felix the Cat",
    # "Casper the Friendly Ghost",
    # "Richie Rich",
    # "Mighty Mouse",
    # "Underdog",
    # "Rocky",
    # "Bullwinkle",
    # "Boris Badenov",
    # "Natasha Fatale",
    # "Dudley Do-Right",
    # "Snidely Whiplash",
    # "Mr. Peabody",
    # "Sherman",
    # "Inspector Gadget",
    # "Penny",
    # "Blue",
    # "Magenta",
    # "Barney",
    # "Bob the Builder",
    # "Wendy",
    # "Scoop",
    # "Muck",
    # "Dizzy",
    # "Roley",
    # "Lofty",
    # "Thomas",
    # "Edward",
    # "Henry",
    # "Gordon",
    # "James",
    # "Percy",
    # "Toby",
    # "Emily",
    # "Diesel",
    # "Mavis",
    # "Rosie",
    # "Sir Topham Hatt",
    # "Postman Pat",
    # "Jess the Cat",
    # "Fireman Sam",
    # "Elvis Cridlington",
    # "Penny Morris",
    # "Station Officer Steele",
    # "Shaun",
    # "Bitzer",
    # "The Farmer",
    # "Shirley",
    # "Timmy",
    # "Wallace",
    # "Gromit",
    # "Feathers McGraw",
    # "Morph",
    # "Pingu",
    # "Pinga",
    # "Robbie",
    # "Barbapapa",
    # "Tinky Winky",
    # "Dipsy",
    # "Laa-Laa",
    # "Po",
    # "Noo-Noo",
    # "Noddy",
    # "Big Ears",
    # "Mr. Tickle",
    # "Mr. Happy",
    # "Mr. Bump",
    # "Mr. Nosey",
    # "Mr. Sneeze",
    # "Mr. Greedy",
    # "Mr. Messy",
    # "Mr. Slow",
    # "Mr. Brave",
    # "Mr. Busy",
    # "Mr. Daydream",
    # "Mr. Forgetful",
    # "Mr. Jelly",
    # "Mr. Lazy",
    # "Mr. Rush",
    # "Mr. Quiet",
    # "Mr. Tall",
    # "Mr. Grumpy",
    # "Mr. Muddle",
    # "Mr. Nonsense",
    # "Mr. Small",
    # "Mr. Chatterbox",
    # "Mr. Rude",
    # "Mr. Cool",
    # "Mr. Good",
    # "Mr. Christmas",
    # "Little Miss Sunshine",
    # "Little Miss Naughty",
    # "Little Miss Bossy",
    # "Little Miss Giggles",
    # "Little Miss Chatterbox",
    # "Little Miss Daredevil",
    # "Little Miss Magic",
    # "Little Miss Lucky",
    # "Little Miss Star",
    # "Little Miss Scary",
    # "Little Miss Hug",
    "Homer Simpson",
    # "Marge Simpson",
    # "Bart Simpson",
    # "Lisa Simpson",
    # "Maggie Simpson",
    # "Ned Flanders",
    # "Montgomery Burns",
    # "Waylon Smithers",
    # "Moe Szyslak",
    # "Barney Gumble",
    # "Krusty the Clown",
    # "Chief Wiggum",
    # "Ralph Wiggum",
    # "Milhouse Van Houten",
    # "Nelson Muntz",
    # "Lenny Leonard",
    # "Carl Carlson",
    # "Abe Simpson",
    # "Patty Bouvier",
    # "Selma Bouvier",
    # "Santa's Little Helper",
    # "Snowball II",
    # "Otto Mann",
    # "Peter Griffin",
    # "Lois Griffin",
    # "Meg Griffin",
    # "Chris Griffin",
    # "Stewie Griffin",
    # "Brian Griffin",
    # "Glenn Quagmire",
    # "Cleveland Brown",
    # "Joe Swanson",
    # "Bonnie Swanson",
    # "Mort Goldman",
    # "Bruce",
    # "Herbert",
    # "Phineas Flynn",
    # "Ferb Fletcher",
    # "Candace Flynn",
    # "Perry the Platypus",
    # "Heinz Doofenshmirtz",
    # "Isabella Garcia-Shapiro",
    # "Baljeet Tjinder",
    # "Buford Van Stomm",
    # "Tom Cat",
    # "Jerry Mouse",
    # "Spike Bulldog",
    # "Tyke Bulldog",
    # "Nibbles",
    # "Droopy",
    # "Pink Panther",
    # "The Inspector",
    # "The Ant",
    # "The Aardvark",
    "Shrek",
    # "Donkey",
    # "Puss in Boots",
    # "Gingy",
    # "Po",
    # "Tigress",
    # "Monkey",
    # "Crane",
    # "Mantis",
    # "Viper",
    # "Shifu",
    # "Alex the Lion",
    # "Marty the Zebra",
    # "Melman the Giraffe",
    # "Gloria the Hippo",
    # "Toothless",
    # "Manny",
    # "Sid",
    # "Diego",
    # "Scrat",
    "Dora the Explorer",
    # "Boots",
    # "Swiper",
    # "Diego Marquez",
    # "Peppa Pig",
    # "George Pig",
    # "Mummy Pig",
    # "Daddy Pig",
    # "Suzy Sheep",
    # "Rebecca Rabbit",
    # "Danny Dog",
    # "Pedro Pony",
    # "Zoe Zebra",
    # "Emily Elephant",
    # "Madame Gazelle",
    # "Miss Rabbit",
    # "Paddington Bear",
    # "Waldo",
    # "Bob the Tomato",
    # "Larry the Cucumber",
    # "Junior Asparagus",
    # "Archibald Asparagus",
    # "Frosty the Snowman",
    # "The Grinch",
    # "Astro Boy",
    # "Speed Racer",
    # "El Chapulín Colorado",
    # "El Chavo",
    # "Babar",
    # "Olive Oyl",
    # "Bluto",
    # "Skeletor",
    # "Orko",
    # "Tenderheart Bear",
    # "Funshine Bear",
    # "Grumpy Bear",
    # "Cheer Bear",
    # "Good Luck Bear",
    # "Share Bear",
    # "Wish Bear",
    # "Friend Bear",
    # "Love-a-Lot Bear",
    # "Bedtime Bear",
    # "Rainbow Brite",
    # "The Tick",
    # "Earthworm Jim",
    # "Spyro",
    # "Banjo",
    # "Kazooie",
    # "Conker",
    # "Ness",
    # "Mr. Saturn",
    # "Monokuma",
    # "Amaterasu",
    # "Phoenix Wright",
    # "Professor Layton",
    "Elmo",
    # "Cookie Monster",
    # "Big Bird",
    # "Grover",
    # "Oscar the Grouch",
    # "Ernie",
    # "Bert",
    # "Count von Count",
    # "Abby Cadabby",
    # "Mr. Bean",
    # "Mafalda",
    # "Domo",
    # "Pucca",
    # "Garu",
]

object_attributes = [
    # Aesthetic and Style
    "futuristic",
    "mechanical",
    "minimalist",
    "sleek",
    "organic",
    "modular",
    "ergonomic",
    "industrial",
    "high-tech",
    "retro",
    "streamlined",
    "geometric",
    "luxurious",
    "eco-friendly",
    "transparent",
    "tactile",
    "sculptural",
    "biophilic",
    "adaptive",
    "compact",
    "dynamic",
    "functional",
    "lightweight",
    "bold",
    "monolithic",
    "seamless",
    "aerodynamic",
    "symmetrical",
    "asymmetrical",
    "soft-edged",
    "multifunctional",
    "customizable",
    "textured",
    "sleek-metallic",
    "high-contrast",
    "artisanal",
    "intuitive",
    "innovative",
    "cutting-edge",
    "parametric",
    "intelligent",
    "hybrid",
    "space-age",
    "bionic",
    "kinetic",
    "foldable",
    "collapsible",
    "interlocking",
    "transformable",
    "smart",
    "wearable",
    "biodegradable",
    "recyclable",
    "high-performance",
    "precision-engineered",
    "sensor-integrated",
    "wireless",
    "compact-folding",
    "hovering",
    "self-healing",
    "adaptive-texture",
    "weather-resistant",
    "shock-absorbing",
    "zero-waste",
    "carbon-neutral",
    "energy-efficient",
    "photochromic",
    "electroluminescent",
    "haptic-feedback",
    "aerospace-grade",
    "high-fidelity",
    "anodized",
    "seamlessly-integrated",
    "robotic",
    "bioengineered",
    "crystalline",
    "chiseled",
    "gradient-finished",
    "superhydrophobic",
    "multi-layered",
    "3D-printed",
    "woven-fiber",
    "graphene-enhanced",
    "carbon-fiber",
    "self-assembling",
    "shape-shifting",
    "nano-coated",
    "sound-absorbing",
    "anti-reflective",
    "liquid-metal",
    "vacuum-sealed",
    "weightless",
    "zero-gravity",
    "hyper-efficient",
    "heat-dissipating",
    "neural-interfaced",
    "interactive",
    "gesture-controlled",
    "magnetically-levitated",
    "force-sensitive",
    "bio-adaptive",
    "retro-futuristic",
    "soft-touch",
    "featherweight",
    "vaporwave-inspired",
    "monochromatic",
    "chromatic",
    "matte-finished",
    "glossy",
    "mirrored",
    "frosted",
    "perforated",
    "breathable",
    "hyperminimal",
    "tunable",
    "eco-luxe",
    "digital-fabricated",
    "kinesthetic",
    # Technology-enhanced
    "AI-powered",
    "machine-learning-optimized",
    "VR-compatible",
    "augmented-reality-enhanced",
    "gesture-responsive",
    "voice-activated",
    "self-calibrating",
    "adaptive-lighting",
    "smart-touch",
    "holographic-display",
    "projection-mapped",
    "biometric-scanning",
    "temperature-sensitive",
    "solar-powered",
    "kinetic-energy-harvesting",
    "self-cleaning",
    "antimicrobial-coated",
    "UV-resistant",
    "impact-responsive",
    "lightweight-carbon",
    "hydrophobic",
    "moisture-wicking",
    "shape-memory-alloy",
    "hyper-elastic",
    "self-repairing",
    "programmable-matter",
    "conductive-fabric",
    "anti-static",
    "fire-resistant",
    "bulletproof-rated",
    # Structural & Functional
    "cantilevered",
    "floating",
    "stackable",
    "interchangeable",
    "telescopic",
    "extendable",
    "articulated",
    "pivoting",
    "reconfigurable",
    "multi-positional",
    "spring-loaded",
    "tension-balanced",
    "magnetic-closing",
    "snap-fit",
    "twist-lock",
    "screwless-assembly",
    "dual-function",
    "hidden-compartment",
    "folding-mechanism",
    "detachable",
    "climate-adaptive",
    "collapsible-storage",
    "rotational-adjustment",
    "shock-mounted",
    "built-in-organizer",
    "quick-release",
    "floating-hinge",
]

product_materials = [
    # Color & Visual
    "neon-accented",
    "monotone",
    "two-tone",
    "gradient-blend",
    "iridescent",
    "camouflage",
    "color-changing",
    "photo-reactive",
    "holographic",
    "metallic-sheen",
    "pastel-hued",
    "dark-mode",
    "luminous",
    "chameleon-finish",
    "smoky-tinted",
    "pearlescent",
    "bold-contrast",
    "opalescent",
    "carbon-black",
    "futuristic-blue",
    "techno-green",
    "gold-trimmed",
    "colorful",
    # Surface & Finishing
    "soft-matte",
    "high-gloss",
    "satin-finish",
    "brushed-finish",
    "hammered-texture",
    "oxidized-patina",
    "engraved",
    "etched",
    "embossed",
    "debossed",
    "sandblasted",
    "laser-cut",
    "perforated-metal",
    "open-weave",
    "woven-leather",
    "handcrafted",
    "hand-painted",
    "raw-finished",
    "polished-concrete",
    "granite-textured",
    "diamond-patterned",
    "gradient-finish",
    "mirror-polished",
    "faux-marble",
    # Design Movements
    "mid-century-modern",
    "art-deco",
    "brutalist",
    "neo-futurist",
    "steampunk",
    "cyberpunk",
    "organic-modern",
    "Scandinavian",
    "Japanese-inspired",
    "industrial-chic",
    "retro-wave",
    "digital-baroque",
    "minimal-brutalist",
    "furniture-inspired",
    "spacecraft-inspired",
    "automotive-inspired",
    "biomimetic",
    "hyper-modern",
    "lux-tech",
    "post-modern",
    "eco-industrial",
    "kinetic-architecture",
    # Material-based
    "titanium",
    "ceramic",
    "marble",
    "woodgrain",
    "sustainable-wood",
    "bamboo",
    "hemp-fabric",
    "vegan-leather",
    "brushed-metal",
    "polished-aluminum",
    "stainless-steel",
    "copper-finished",
    "brass-inlaid",
    "gunmetal",
    "weathered-bronze",
    "patina-coated",
    "soft-fabric",
    "woven-texture",
    "cork-based",
    "recycled-plastic",
    "hemp-composite",
    "plant-based-polymer",
    "nano-fiber",
    "bio-synthetic",
    "crystal-clear-acrylic",
    "translucent-polycarbonate",
    "frosted-glass",
    "tempered-glass",
    "fiber-reinforced",
    "carbon-nanotube",
    "reinforced-polymer",
]

product_defining_attributes = [
    "with an integrated screen",
    "with an interactive touchscreen",
    "with LED lighting",
    "with a digital display",
    "with physical knobs",
    "with button controls",
    "with a lever mechanism",
    "with dials and meters",
    "with a switch panel",
    "with exposed circuits",
    "with a USB port",
    "with wireless charging",
    "with a plug-in power source",
    "with a hinged component",
    "with rotary dials",
    "with a joystick control",
    "with built-in speakers",
    "with sensor activation",
    "with remote control functionality",
    "with a folding mechanism",
    "with visible gears and cogs",
    "with a spring-loaded mechanism",
    "with exposed wiring",
    "with a motorized function",
    "with a rechargeable battery",
    "with adjustable settings",
    "with a telescopic extension",
    "with pressure-sensitive controls",
    "with haptic feedback",
    "with a heat-reactive surface",
    "with voice control",
    "with an integrated camera",
    "with built-in lighting",
    "with a cooling fan",
    "with a vented design",
    "with mechanical arms",
    "with a push-button start",
    "with a laser guide",
    "with a projection system",
    "with an augmented reality display",
    "with an infrared sensor",
    "with a biometric scanner",
    "with motion detection",
    "with magnetic attachments",
    "with a robotic joint system",
    "with a swiveling base",
    "with a wearable strap",
    "with an extendable arm",
    "with a hinged lid",
    "with detachable modules",
    "with a dual-screen display",
    "with a charging dock",
    "with an input interface",
    "with a force-sensitive surface",
    "with a scroll wheel",
    "with adjustable knobs",
    "with a mechanical keyboard",
    "with gesture-responsive controls",
    "with programmable functions",
    "with smartphone compatibility",
    "with modular add-ons",
    "with automatic adjustments",
    "with fluid dynamics",
    "with a hydraulic system",
    "with pneumatic controls",
    "with temperature regulation",
    "with a vacuum-sealed mechanism",
    "with a pressure gauge",
    "with indicator lights",
    "with an audio jack",
    "with a charging port",
    "with a removable battery",
    "with a solar panel",
    "with a self-leveling system",
    "with auto-calibration",
    "with gyroscopic stabilization",
    "with a built-in trackpad",
    "with a wired connection",
    "with swipe controls",
    "with multi-touch gestures",
    "with programmable LED lighting",
    "with laser-cut details",
    "with an ergonomic handle for grip",
    "with a fastening system",
    "with a clamp mount",
    "with a clip-on attachment",
    "with a cartridge-based system",
    "with replaceable components",
    "with a screw-driven mechanism",
    "with a lever operation",
    "with a fingerprint scanner",
    "with an AI-powered interface",
    "with an auto-docking feature",
    "with a rotating mechanism",
    "with expandable storage",
    "with a plug-and-play setup",
    "with a barcode scanner",
    "with a tactile click wheel",
]

animals = [
    "aardvark",
    "alligator",
    "alpaca",
    "antelope",
    "armadillo",
    "badger",
    "bat",
    "bear",
    "beaver",
    "bison",
    "boar",
    "buffalo",
    "camel",
    "capybara",
    "caracal",
    "cat",
    "cheetah",
    "chimpanzee",
    "chinchilla",
    "chipmunk",
    "cougar",
    "coyote",
    "crab",
    "crocodile",
    "deer",
    "dhole",
    "dingo",
    "dog",
    "dolphin",
    "donkey",
    "dormouse",
    "dugong",
    "eagle",
    "echidna",
    "elephant",
    "elk",
    "ermine",
    "ferret",
    "fish",
    "fox",
    "frog",
    "gazelle",
    "gecko",
    "gibbon",
    "giraffe",
    "goat",
    "gorilla",
    "groundhog",
    "guinea pig",
    "hamster",
    "hare",
    "hedgehog",
    "hippopotamus",
    "horse",
    "hyena",
    "ibex",
    "iguana",
    "impala",
    "jackal",
    "jaguar",
    "jellyfish",
    "kangaroo",
    "koala",
    "komodo dragon",
    "kudu",
    "lemur",
    "leopard",
    "lion",
    "llama",
    "lobster",
    "lynx",
    "manatee",
    "marmoset",
    "meerkat",
    "mink",
    "mole",
    "mongoose",
    "monkey",
    "moose",
    "mouse",
    "narwhal",
    "ocelot",
    "octopus",
    "okapi",
    "opossum",
    "orangutan",
    "otter",
    "owl",
    "panda",
    "pangolin",
    "panther",
    "parrot",
    "peacock",
    "pelican",
    "penguin",
    "pig",
    "platypus",
    "polar bear",
    "porcupine",
    "possum",
    "puma",
    "quokka",
    "quoll",
    "rabbit",
    "raccoon",
    "rat",
    "reindeer",
    "rhinoceros",
    "salamander",
    "scorpion",
    "seal",
    "serval",
    "shark",
    "sheep",
    "skunk",
    "sloth",
    "snail",
    "snake",
    "snow leopard",
    "squirrel",
    "starfish",
    "stingray",
    "swan",
    "tamarin",
    "tapir",
    "tarsier",
    "tasmanian devil",
    "tiger",
    "toad",
    "tortoise",
    "toucan",
    "turkey",
    "turtle",
    "viper",
    "walrus",
    "warthog",
    "weasel",
    "whale",
    "wolf",
    "wolverine",
    "wombat",
    "woodpecker",
    "yak",
    "zebra",
]

outfit_adjectives = [
    "adorable",
    "aesthetic",
    "artsy",
    "attractive",
    "bold",
    "bohemian",
    "breezy",
    "casual",
    "charming",
    "chic",
    "classic",
    "classy",
    "colorful",
    "comfy",
    "cool",
    "coordinated",
    "cozy",
    "cute",
    "daring",
    "dapper",
    "dainty",
    "delicate",
    "dramatic",
    "elegant",
    "ethereal",
    "exotic",
    "fancy",
    "fashionable",
    "flashy",
    "flattering",
    "floral",
    "formal",
    "funky",
    "futuristic",
    "gorgeous",
    "graceful",
    "grunge",
    "hip",
    "iconic",
    "laid-back",
    "lavish",
    "lively",
    "luxurious",
    "minimalist",
    "modern",
    "monochrome",
    "neat",
    "neutral",
    "old-school",
    "opulent",
    "ornate",
    "pastel",
    "playful",
    "polished",
    "preppy",
    "quirky",
    "radiant",
    "refined",
    "relaxed",
    "retro",
    "romantic",
    "rustic",
    "sleek",
    "sophisticated",
    "sporty",
    "statement-making",
    "streetwear",
    "stunning",
    "stylish",
    "suave",
    "sunny",
    "tasteful",
    "timeless",
    "trendy",
    "ultra-modern",
    "understated",
    "vibrant",
    "vintage",
    "whimsical",
]

professions = [
    "accountant",
    "actor",
    "actuary",
    "advertiser",
    "aerospace engineer",
    "agriculturist",
    "air traffic controller",
    "airline pilot",
    "animator",
    "anthropologist",
    "app developer",
    "archeologist",
    "architect",
    "archivist",
    "artist",
    "astronaut",
    "astronomer",
    "athlete",
    "author",
    "baker",
    "banker",
    "barber",
    "bartender",
    "biochemist",
    "biologist",
    "blacksmith",
    "blogger",
    "bookkeeper",
    "botanist",
    "bricklayer",
    "broker",
    "builder",
    "butcher",
    "cab driver",
    "calligrapher",
    "car mechanic",
    "carpenter",
    "cartographer",
    "cashier",
    "chef",
    "chemist",
    "chiropractor",
    "cinematographer",
    "civil engineer",
    "climatologist",
    "coach",
    "comedian",
    "composer",
    "computer programmer",
    "conductor",
    "construction worker",
    "consultant",
    "content creator",
    "copywriter",
    "counselor",
    "court reporter",
    "critic",
    "curator",
    "customer service representative",
    "dancer",
    "data analyst",
    "data scientist",
    "dentist",
    "dermatologist",
    "detective",
    "dietitian",
    "director",
    "diver",
    "doctor",
    "drone operator",
    "economist",
    "editor",
    "electrician",
    "engineer",
    "entrepreneur",
    "environmentalist",
    "epidemiologist",
    "event planner",
    "executive",
    "farmer",
    "fashion designer",
    "film director",
    "financial advisor",
    "firefighter",
    "fisherman",
    "fitness trainer",
    "flight attendant",
    "florist",
    "forensic scientist",
    "game developer",
    "gardener",
    "geneticist",
    "geologist",
    "glassblower",
    "goldsmith",
    "graphic designer",
    "guitarist",
    "hairdresser",
    "historian",
    "home inspector",
    "hospice worker",
    "hotel manager",
    "human resources specialist",
    "illustrator",
    "industrial designer",
    "interior designer",
    "interpreter",
    "investigator",
    "IT specialist",
    "jeweler",
    "journalist",
    "judge",
    "landscape architect",
    "librarian",
    "linguist",
    "locksmith",
    "magician",
    "makeup artist",
    "marine biologist",
    "marketing manager",
    "martial arts instructor",
    "mathematician",
    "mechanic",
    "meteorologist",
    "midwife",
    "military officer",
    "model",
    "musician",
    "nail technician",
    "neurologist",
    "nurse",
    "nutritionist",
    "oceanographer",
    "optometrist",
    "paleontologist",
    "paramedic",
    "paralegal",
    "park ranger",
    "pastor",
    "pediatrician",
    "personal trainer",
    "pet groomer",
    "pharmacist",
    "photographer",
    "physical therapist",
    "physicist",
    "pilot",
    "plumber",
    "poet",
    "police officer",
    "politician",
    "private investigator",
    "producer",
    "professor",
    "programmer",
    "psychologist",
    "public relations specialist",
    "publisher",
    "radiologist",
    "real estate agent",
    "referee",
    "researcher",
    "restaurateur",
    "robotics engineer",
    "sailor",
    "sculptor",
    "scientist",
    "screenwriter",
    "scuba instructor",
    "secretary",
    "security guard",
    "social media manager",
    "social worker",
    "software developer",
    "soldier",
    "songwriter",
    "speech therapist",
    "statistician",
    "stockbroker",
    "subway operator",
    "surgeon",
    "surveyor",
    "tailor",
    "taxidermist",
    "taxi driver",
    "teacher",
    "technical writer",
    "therapist",
    "tour guide",
    "translator",
    "truck driver",
    "TV host",
    "urban planner",
    "veterinarian",
    "videographer",
    "virologist",
    "vlogger",
    "waiter",
    "watchmaker",
    "web designer",
    "welder",
    "wildlife biologist",
    "winemaker",
    "writer",
    "yoga instructor",
    "zookeeper",
    "zoologist",
    "superhero",
    "pirate",
    "ninja",
]

clothing_items = [
    # Tops
    [
        "shirt",
        "sweater",
        "t-shirt",
        "blouse",
        "tank top",
        "hoodie",
        "cardigan",
        "jacket",
        "vest",
        "polo shirt",
        "long-sleeve shirt",
        "tunic",
        "coat",
    ],
    # Bottoms
    [
        "pants",
        "jeans",
        "shorts",
        "skirt",
        "leggings",
        "cargo pants",
        "sweatpants",
        "trousers",
        "joggers",
        "overalls",
        "dungarees",
    ],
    # Hair Styles
    [
        "spiky hair",
        "flowing hair",
        "curly hair",
        "ponytail",
        "braided hair",
        "buzz cut",
        "mohawk",
        "wavy hair",
        "afro",
        "dreadlocks",
        "bob cut",
        "buns",
        "side part",
    ],
    # Eyewear
    ["glasses", "sunglasses", "goggles", "reading glasses", "aviator sunglasses", "round glasses", "sports sunglasses"],
    # Footwear
    [
        "sneakers",
        "boots",
        "sandals",
        "loafers",
        "flip-flops",
        "hiking boots",
        "cowboy boots",
        "slippers",
        "running shoes",
        "rain boots",
    ],
    # Hats & Headwear
    [
        "baseball cap",
        "beanie",
        "fedora",
        "beret",
        "bucket hat",
        "headband",
        "visor",
        "crown",
        "sun hat",
        "knit cap",
        "party hat",
    ],
    # Outerwear
    [
        "coat",
        "raincoat",
        "parka",
        "leather jacket",
        "bomber jacket",
        "windbreaker",
        "denim jacket",
        "poncho",
        "puffer jacket",
    ],
    # Accessories
    [
        "belt",
        "scarf",
        "tie",
        "bowtie",
        "gloves",
        "watch",
        "bracelet",
        "necklace",
        "earrings",
        "rings",
        "backpack",
        "waist bag",
        "mittens",
    ],
    # Undergarments (General & Child-Friendly)
    ["undershirt", "tights", "long johns", "socks", "fuzzy socks"],
    # Formalwear
    ["suit", "tuxedo", "gown", "blazer", "dress shirt", "fancy dress", "bow tie"],
    # Sleepwear
    ["pajamas", "nightgown", "robe", "slippers", "sleep mask"],
    # Swimwear (Child-Friendly)
    ["swimsuit", "swim trunks", "one-piece swimsuit", "rash guard", "swim cap"],
    # Traditional Clothing
    ["kimono", "hanbok", "kilt", "dashiki", "poncho", "dirndl", "cheongsam", "kaftan", "sarong"],
]


plush_colors = [
    # Primary Colors
    "red",
    "blue",
    "yellow",
    # Secondary Colors
    "green",
    "orange",
    "purple",
    # Tertiary Colors
    "cyan",
    "magenta",
    "lime",
    "teal",
    "violet",
    "amber",
    # Common Shades
    "pink",
    "brown",
    "gray",
    "black",
    "white",
    # Light & Soft Shades
    "light blue",
    "light green",
    "light pink",
    "light purple",
    "peach",
    "mint",
    "cream",
    "lavender",
    "baby blue",
    "pastel yellow",
    "powder blue",
    "pastel orange",
    "pastel purple",
    "blush",
    "sky blue",
    "rose",
    "periwinkle",
    # Dark & Rich Shades
    "dark blue",
    "dark green",
    "dark red",
    "navy blue",
    "forest green",
    "maroon",
    "burgundy",
    "charcoal",
    "midnight blue",
    "deep purple",
    "chocolate",
    "mahogany",
    "olive green",
    "cobalt blue",
    "plum",
    "deep teal",
    # Metallic & Shiny Colors
    "gold",
    "silver",
    "bronze",
    "copper",
    "pearl",
    "rose gold",
    # Fun & Unique Names
    "sunset orange",
    "neon pink",
    "electric blue",
    "lemon yellow",
    "bubblegum pink",
    "coral",
    "turquoise",
    "ruby red",
    "sapphire blue",
    "emerald green",
    "cotton candy pink",
    "fire engine red",
    "pumpkin orange",
    "ocean blue",
    "strawberry red",
    "minty green",
    "sand beige",
    "rainbow",
    "glittery gold",
    "shimmering silver",
    # Nature-Inspired Colors
    "grass green",
    "sky blue",
    "sea green",
    "sunflower yellow",
    "cherry red",
    "rose pink",
    "ocean teal",
    "desert sand",
    "earth brown",
    "cloud white",
    "pine green",
    "daisy yellow",
    "grape purple",
    "watermelon pink",
    "sunset purple",
    # Transparent & Special Colors
    "transparent",
    "glowing neon",
    "sparkling rainbow",
]

plush_items = [
    # Musical Instruments
    "guitar",
    "piano",
    "drum",
    "violin",
    "trumpet",
    "saxophone",
    "microphone",
    "ukulele",
    "accordion",
    "flute",
    "xylophone",
    "harmonica",
    "tambourine",
    "cymbals",
    "maracas",
    "clarinet",
    "triangle",
    "cello",
    "banjo",
    "synthesizer",
    # Books & Learning
    "book",
    "notebook",
    "alphabet block",
    "chalkboard",
    "globe",
    "pencil",
    "crayon",
    "paintbrush",
    "easel",
    "calculator",
    "quill and scroll",
    "magnifying glass",
    "ruler",
    "clipboard",
    "compass",
    "abacus",
    "map",
    "hourglass",
    "diploma scroll",
    # Fruits & Food Plushies
    "apple",
    "banana",
    "strawberry",
    "watermelon",
    "pineapple",
    "grape bunch",
    "cherry",
    "avocado",
    "cupcake",
    "chocolate bar",
    "ice cream cone",
    "donut",
    "marshmallow",
    "sushi roll",
    "croissant",
    "pancake stack",
    "boba tea",
    "pumpkin",
    "carrot",
    "candy cane",
    "hot cocoa mug",
    "milkshake",
    "burger",
    "french fries",
    "pizza slice",
    "pretzel",
    "taco",
    "corn on the cob",
    "onigiri",
    "honey jar",
    "tea cup",
    "cookie",
    # Everyday Objects
    "heart",
    "star",
    "moon",
    "cloud",
    "sun",
    "flower",
    "tree",
    "mushroom",
    "pillow",
    "lamp",
    "clock",
    "cactus",
    "snowflake",
    "key",
    "treasure chest",
    "paint palette",
    "diamond",
    "feather",
    "potion bottle",
    "rainbow",
    "umbrella",
    "lantern",
    "magic wand",
    "telescope",
    "laptop",
    "phone",
    "camera",
    "robot",
    "parachute",
    "binoculars",
    "paper airplane",
    "balloon",
    "kite",
    "anchor",
    "lifebuoy",
    # Holiday & Special Plushies
    "Christmas tree",
    "snowman",
    "Easter bunny",
    "Halloween pumpkin",
    "birthday cake",
    "fireworks",
    "gift box",
    "valentine heart",
    "party hat",
    "champagne bottle",
    "jack-o'-lantern",
    "gingerbread man",
    "candy apple",
    "menorah",
    "stocking",
    # Space & Sci-Fi
    "rocket ship",
    "UFO",
    "astronaut helmet",
    "satellite",
    "planet",
    "meteor",
    "starship",
    # Sports & Hobbies
    "soccer ball",
    "basketball",
    "baseball glove",
    "tennis racket",
    "skateboard",
    "fishing rod",
    "paintbrush",
    "video game controller",
    "chess piece",
    "yoyo",
    "jump rope",
]

plush_items = [
    # Musical Instruments
    "guitar",
    "piano",
    "drum",
    "violin",
    "trumpet",
    "saxophone",
    "microphone",
    "ukulele",
    "accordion",
    "flute",
    "xylophone",
    "maracas",
    "harmonica",
    # Books & Learning
    "book",
    "notebook",
    "alphabet block",
    "chalkboard",
    "globe",
    "pencil",
    "crayon",
    "paintbrush",
    "easel",
    "calculator",
    "quill and scroll",
    "magnifying glass",
    "ruler",
    "map",
    "clipboard",
    "compass (drawing tool)",
    "flashcards",
    # Tools & Everyday Objects
    "wrench",
    "hammer",
    "screwdriver",
    "tape measure",
    "saw",
    "pliers",
    "paint roller",
    "flashlight",
    "whistle",
    "toolbox",
    "binoculars",
    "key",
    "lantern",
    "lock",
    "potion bottle",
    "watering can",
    "magic wand",
    "fishing rod",
    "bucket",
    # Food & Drinks
    "apple",
    "banana",
    "strawberry",
    "watermelon",
    "pineapple",
    "grape bunch",
    "cherry",
    "cupcake",
    "chocolate bar",
    "ice cream cone",
    "donut",
    "marshmallow",
    "sushi roll",
    "croissant",
    "pancake stack",
    "boba tea",
    "pumpkin",
    "carrot",
    "lollipop",
    "cookie",
    "sandwich",
    "milk carton",
    "teacup",
    "mug",
    "juice box",
    "butter toast",
    "pie",
    "hot cocoa cup",
    "honey jar",
    # Toys & Playtime
    "rubber duck",
    "toy car",
    "wooden block",
    "yo-yo",
    "jump rope",
    "ball",
    "kite",
    "toy train",
    "marble",
    "toy boat",
    "spinning top",
    "toy airplane",
    "stuffed heart",
    "tiny plush doll",
    "balloon",
    "beach ball",
    "tiny drum",
    "wind-up toy",
    # Sports & Outdoor Fun
    "soccer ball",
    "basketball",
    "baseball bat",
    "tennis racket",
    "ping pong paddle",
    "volleyball",
    "badminton racket",
    "roller skate",
    "frisbee",
    "football",
    "hiking stick",
    "compass",
    "trophy",
    "whistle",
    "small fishing net",
    # Wearable Accessories
    "scarf",
    "hat",
    "mittens",
    "gloves",
    "headphones",
    "bowtie",
    "watch",
    "necklace",
    "sunglasses",
    "backpack",
    "camera",
    "fanny pack",
    "umbrella",
    "walking cane",
    "crown",
    "party hat",
    # Art & Creativity
    "paintbrush",
    "paint palette",
    "sketchbook",
    "camera",
    "sticker sheet",
    "origami paper",
    "box of crayons",
    "marker",
    "glue stick",
    "glitter shaker",
    "craft scissors",
    "coloring book",
    "tape dispenser",
    # Seasonal & Themed
    "gift box",
    "snow globe",
    "pumpkin lantern",
    "candy cane",
    "fireworks sparkler",
    "wrapped candy",
    "party horn",
    "birthday cake slice",
    "tiny wrapped present",
    "heart-shaped box",
    # Miscellaneous Fun
    "tiny telescope",
    "plush pillow",
    "wooden spoon",
    "feather quill",
    "pocket watch",
    "hand mirror",
    "paper fan",
    "scroll",
    "treasure map",
    "coin pouch",
    "ticket stub",
    "tiny bell",
    "scented candle",
    "wishing star",
    "small radio",
]


plush_keywords = ["clothes"]
