dataset_path: './datasets/generated/IndoorLayout_train'
val_dataset_path: './datasets/generated/IndoorLayout_val'
output_dir: './training_results/train_IndoorLayout'
train_batch_size: 4
num_layers: 4
max_crops: 8